# docker-compose.yml
services:
  ddns:
    image: ddns-flask
    container_name: ddns-flask
    restart: always
    ports:
      - "5000:8080"
    volumes:
      - ./app/config.json:/app/config.json
      - ./app/ddns_addresses.txt:/app/ddns_addresses.txt
